### ISSUE TITLE
Xtreme1 Release 0.5.5

### ISSUE THREAD

**Issue by ToMaToJ** [xtreme1-io/xtreme1#81]
### Overview
Release 0.5.5 takes the first step into the Scenario Search, APIs, Ontology Center, Ontology Fusion, and Data Visualizations. All of them are fundamental modules of Xtreme1. We would greatly appreciate any issues, discussions,  and contributions as an open and community-driven project.

### Release Date

Tag v0.5.5 2022/12/26

### Data Visualization

This module is planning to visualize  data in the following aspects:

- Data statistics level
- Raw data level
- Annotation data level
- Object level 

The target of this release:
- At the data statistics level:
   - [x] Basic metrics of the dataset 
   - [x] Distribution chart of data by class and classification
   - [x] Similarity map for the Image dataset
   - [ ] Similarity map for LiDAR and LiDAR fusion dataset 
- At raw data level:
  - [x] Raw data visualization for both image and LiDAR dataset
  - [x] Annotation data visualization for both image and LiDAR dataset     
- At the annotation data level:
  - [x] Preview annotation results in the dataset for both the image and LiDAR dataset

- At the object level:
   Will be included in scenario search

### Data import and export

- [x] Support COCO format for the image dataset

Xtreme1 will provide a script to convert Xtreme1 format to COCO format now: https://github.com/xtreme1-io/xtreme1-SDK, and later will support a function and SDK to support mutual conversion  between COCO to Xtreme1

Related Issues:
- [ ] https://github.com/xtreme1-io/xtreme1/issues/55 

### Scenario Search

Scenario Search will solve the problem of how we define and find desired data or a part of data explicitly at the situation and scenario level

We normally curate data at the data or object level which raises the problem that curating data by data level will be too general to find a concrete issue in your data, meanwhile, at the object level, objects are too isolated to avoid duplicates and to find connections with other objects. The scenario search feature defines objects by labels and attributes and defines scenarios by objects, relations between objects, and object attention. You would be very easy to define and find scenarios like Lane Changes, Parking, U-turns, and Runway Incursion.

![图片](https://user-images.githubusercontent.com/10492049/210691696-985c822d-bc6d-45e8-b7f2-c04ca165e2ba.gif)

The target of this release:

- [x] Search scenarios by classes and classification in a specific dataset(image and LiDAR)
- [x] Search scenarios by classes in the ontology center(image and LiDAR)
- [x] Export search results as a JSON file or a new dataset 

In future releases:

- Will support relation annotation and scenario search by objects and relations
- Will support attributes search in scenario search by objects, relations, and attributes.

### Ontology Center

Ontology Center is designed to: 

- Manage your ontologies and data across all datasets.
- Provide industrial templates and solutions for your annotation and model training

The target of this release:

- [x] CRUD ontologies and their classes and classifications in the ontology center
- [x] Ontology fusion at the data storage level between classes in the dataset and classes in the ontology center
- [x] Ontology export and import both in the ontology center and the dataset
- [x] Copy classes and classifications from the ontology center
- [x] Push, pull classes' attributes between classes in the dataset and ontology
- [x] Scenario search across all datasets of the same dataset type 

### APIs & SDK

Xtreme1 is planning to provide full API and SDK suites for integration

The target of this release:

- [x] Provides My APIs page to manage API tokens
- [x] Provides fundamental APIs and docs, you can find our APIs docs [here](https://docs.xtreme1.io/xtreme1-docs/developer-reference/api-document)
- [ ] Provides SDK based on APIs

**Comment by ToMaToJ** [comment]
Released
